
import React, { useState, useEffect, useCallback } from 'react';
import Header from './components/Header';
import UbuntuIntegration from './components/UbuntuIntegration';
import { Wallpaper } from './types';
import { fetchWallpapers } from './services/wallpaperService';
import { generateAIWallpaper } from './services/geminiService';

const App: React.FC = () => {
  const [wallpapers, setWallpapers] = useState<Wallpaper[]>([]);
  const [selectedWallpaper, setSelectedWallpaper] = useState<Wallpaper | null>(null);
  const [loading, setLoading] = useState(true);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');

  const loadData = useCallback(async () => {
    try {
      setLoading(true);
      const data = await fetchWallpapers();
      setWallpapers(data);
      if (data.length > 0) setSelectedWallpaper(data[0]);
    } catch (error) {
      console.error("Failed to load wallpapers", error);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const handleGenerateAI = async () => {
    if (!aiPrompt.trim()) return;
    try {
      setAiLoading(true);
      const url = await generateAIWallpaper(aiPrompt);
      const newWallpaper: Wallpaper = {
        id: `ai-${Date.now()}`,
        url: url,
        thumbnail: url,
        title: aiPrompt,
        description: 'Generated by Gemini AI for your Ubuntu Desktop.',
        source: 'AI',
        date: new Date().toISOString().split('T')[0]
      };
      setWallpapers(prev => [newWallpaper, ...prev]);
      setSelectedWallpaper(newWallpaper);
      setAiPrompt('');
    } catch (error) {
      alert("Failed to generate AI image. Ensure your API Key is valid.");
    } finally {
      setAiLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#1a1a1a]">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-[#E95420] border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-gray-400 font-medium animate-pulse">Fetching today's beauty...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen max-w-7xl mx-auto px-4 pb-20">
      <Header />

      <main className="grid grid-cols-1 lg:grid-cols-12 gap-8 mt-8">
        {/* Left Section: Featured & List */}
        <div className="lg:col-span-8 space-y-8">
          {selectedWallpaper && (
            <div className="relative group rounded-3xl overflow-hidden shadow-2xl ring-1 ring-white/10">
              <img 
                src={selectedWallpaper.url} 
                alt={selectedWallpaper.title}
                className="w-full aspect-video object-cover transition-transform duration-700 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent flex flex-col justify-end p-8">
                <span className="text-xs font-bold uppercase tracking-wider bg-[#E95420] px-3 py-1 rounded-full w-fit mb-3">
                  {selectedWallpaper.source} • {selectedWallpaper.date}
                </span>
                <h2 className="text-3xl font-black text-white">{selectedWallpaper.title}</h2>
                <p className="text-gray-300 mt-2 max-w-2xl">{selectedWallpaper.description}</p>
                <div className="mt-6 flex items-center gap-4">
                  <a 
                    href={selectedWallpaper.url} 
                    download 
                    className="ubuntu-gradient px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:opacity-90 transition-opacity"
                  >
                    <i className="fas fa-download"></i> Download 4K
                  </a>
                </div>
              </div>
            </div>
          )}

          <UbuntuIntegration wallpaper={selectedWallpaper} />

          {/* AI Generation Section */}
          <section className="glass p-8 rounded-3xl border border-[#E95420]/20">
            <h3 className="text-xl font-bold flex items-center gap-2 mb-4">
              <i className="fas fa-magic text-[#E95420]"></i> AI Dreamscapes
            </h3>
            <p className="text-gray-400 mb-6 text-sm">Can't find the perfect photo? Let Gemini create a unique 4K wallpaper based on your mood.</p>
            <div className="flex gap-2">
              <input 
                type="text" 
                placeholder="e.g. 'Cyberpunk Tokyo in the rain at night, neon lights reflections'" 
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                disabled={aiLoading}
                className="flex-1 bg-black/40 border border-white/10 rounded-xl px-4 py-3 focus:outline-none focus:border-[#E95420] transition-colors text-white"
              />
              <button 
                onClick={handleGenerateAI}
                disabled={aiLoading}
                className="bg-white text-black px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-gray-200 disabled:opacity-50 transition-all"
              >
                {aiLoading ? <i className="fas fa-circle-notch animate-spin"></i> : <i className="fas fa-wand-sparkles"></i>}
                {aiLoading ? 'Dreaming...' : 'Generate'}
              </button>
            </div>
          </section>
        </div>

        {/* Right Section: Gallery/History */}
        <div className="lg:col-span-4 space-y-6">
          <h3 className="text-xl font-bold flex items-center gap-2 px-2">
            <i className="fas fa-images text-gray-500"></i> Daily Gallery
          </h3>
          <div className="grid grid-cols-1 gap-4 overflow-y-auto max-h-[1200px] pr-2 custom-scrollbar">
            {wallpapers.map((wp) => (
              <div 
                key={wp.id}
                onClick={() => setSelectedWallpaper(wp)}
                className={`group cursor-pointer rounded-2xl overflow-hidden glass transition-all border-2 ${selectedWallpaper?.id === wp.id ? 'border-[#E95420]' : 'border-transparent hover:border-white/10'}`}
              >
                <div className="flex p-3 gap-4">
                  <div className="w-24 h-16 rounded-lg overflow-hidden flex-shrink-0">
                    <img src={wp.thumbnail} alt={wp.title} className="w-full h-full object-cover group-hover:scale-110 transition-transform" />
                  </div>
                  <div className="flex flex-col justify-center min-w-0">
                    <h4 className="font-bold text-sm truncate">{wp.title}</h4>
                    <p className="text-xs text-gray-500 mt-1">{wp.source} • {wp.date}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
      
      {/* Quick Footer */}
      <footer className="mt-20 py-8 border-t border-white/10 flex flex-col items-center justify-center gap-4">
        <div className="flex gap-6 text-gray-400">
          <a href="#" className="hover:text-[#E95420] transition-colors"><i className="fab fa-github"></i> Github</a>
          <a href="#" className="hover:text-[#E95420] transition-colors"><i className="fab fa-twitter"></i> Updates</a>
        </div>
        <p className="text-xs text-gray-500">
          Built with Gemini AI & Ubuntu Design Principles. Not affiliated with Microsoft or Canonical.
        </p>
      </footer>
    </div>
  );
};

export default App;
